[package]
name = "rarithm"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }

[build-dependencies]
bindgen = "0.65.1"
cc = "1.0.99"
